service: andreas-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
    
plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
  dotenv:
    path: .env.${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: false
    format: 'esm'
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
    sourcemap: true

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - http://localhost:3000
              - https://your-production-domain.com
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
    timeout: 30
    memorySize: 1024